# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd /home/vsts/work/1/s/examples
    .//home/vsts/work/1/s/examples/markStaleWorkItem.ps1 -organization https://dev.azure.com/ava-modern-engineering-tests -assignedTo micaela.a.w.syjuco@avanade.com -daysUntilStale 30 -daysUntilClose 60
    echo Completed
  displayName: 'Run Az DevOps CLI'
