# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    az devops project list --org https://dev.azure.com/ava-modern-engineering-tests
  displayName: 'Run Az DevOps CLI'
  workingDirectory: /home/vsts/work/1/s/examples
